name: Deploy Facilities MF Bundle to S3

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Validate and load .env
        run: |
          echo "ðŸ” Checking .env file..."

          if [ ! -f .env ]; then
            echo "âŒ .env file not found"
            exit 1
          fi

          if ! grep -q "^S3_PREFIX=" .env; then
            echo "âŒ S3_PREFIX not found in .env"
            exit 1
          fi

          export $(grep -v '^#' .env | xargs)
          echo "S3_PREFIX=$S3_PREFIX" >> $GITHUB_ENV
          echo "âœ… Loaded S3_PREFIX=$S3_PREFIX"

      - name: Install dependencies
        run: npm i -f

      - name: Build MF bundle
        run: npm run build-mf
        # - npm run build-standalone

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Upload MF bundle to S3
        run: |
          S3_PATH=$(echo "$S3_PREFIX" | sed -E 's|https://([^.]+)\.s3[^/]*\.amazonaws\.com/?|s3://\1/|')

          echo "ðŸ“¦ Uploading MF bundle to: ${S3_PATH}/facilitiesMF/1.1/mf"

          aws s3 cp dist-mf/ "${S3_PATH}/facilitiesMF/1.1/mf" --recursive
